language: node_js
node_js:
- '5'
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: slupw0UhRq5kSWDWt6HwIH6+5ymNsz4AgFFndF+HiOpV5U8cj5TZ/DE9Bvvn5cGW7O8yDXxIrbfjpIGbHOki5ytzs6aqfSsEgHEkSLPZUdRhMolAxD0OLU8y+uzFWqBDmYeKi4E7f+HD9H0JemzrSDrI5vLjYAW3MCAW5RzkQvk0oPCdh46ChlNHPBLly/WO8bl2pL1YOFTTvsoKCRZikw2E9I1bS4LNnJxIuG3VQI4NSn7uOiAkidy9OFGly7uOX+hlMN6NVXms3iVX+hpHtBemFEu4LUyQ1mMDa2JaGXDVPTkMfSpnfQmt9LUexEC/XY7unmS2+wuDaWFBLidfwrdryK1IM06a0xCdT4bprlNYlau+CpBLs2XKYAPxNPP4/j2ZHHm8eODRPfwdz0IuHa0Jk6u57UjtHbzqVMDrRHWZ7fcySRMuWc7azcEdEiwblV8A9KJDhGMxc44J61sZ3SorzQAKX0Ghez4Ub6o0cRk7VUZUtTUBSvrFTwAIlQppf2CBll6JF3kqDCz9TuGLL+uXmjGgsM/lnKYrsrWIf1ZwuRhyqUjPZqgn7a02PN7hUi2axi6WUHf6ZCMUnpyb5RqvcYnQiWntEKbIuy4/qXhwm/4mRZBqM8C9004uE/o/kiNfhdda2r4Klk+Cn8m7ijbYpT4EeXPs50Ga/ImitiY=
  on:
    tags: true
    branches: true
